-- =====================================================================
-- Nerdy Town — NPC residents (optional)
-- Run AFTER schema.sql. NPCs are tagged "NPC" on their profile, answer requests after a
-- few seconds, have no socials and never pay out $NERDY.
-- To remove them later:  delete from public.profiles where is_bot;
-- =====================================================================

select set_config('nerdy.internal', 'on', true);

insert into public.profiles
  (id, is_bot, name, age, gender, looking_for, city, nerd_class, tagline, bio, interests, avatar, verified, rejections_given, rejections_received, accepts, created_at)
values
  ('56fd6e7c-3db7-4f17-ad91-31c545c5e77c', true, 'Ada Byteworth', 24, 'Woman', 'Everyone', 'Brooklyn, NY', 'Code Wizard', 'Will debug your heart in O(1).', 'Backend dev by day, synth-wave producer by night. I rewrote my toaster firmware. It is now faster and slightly sentient.', array['Rust', 'Mech keyboards', 'Tea'], '{"hair":"#22d3ee","skin":"#9a6440","bg":["#ff7a1a","#ff4d8d"],"glasses":"thick","frame":"#065f46","hairStyle":"long","teeth":"grin","freckles":false,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '0 hours'),
  ('2669578b-1b34-4f54-af89-13998b7815b0', true, 'Milo Quark', 27, 'Man', 'Woman', 'Austin, TX', 'Lab Rat', 'Particle physics & pizza rolls.', 'PhD student. Currently teaching a neural net to tell apart cats and croissants. Accuracy: 51%. Ask me about quarks, I dare you.', array['Physics', 'Lego Technic', 'Pizza'], '{"hair":"#e8e1d9","skin":"#e7a978","bg":["#ff7a1a","#ff4d8d"],"glasses":"thick","frame":"#b45309","hairStyle":"bowl","teeth":"one","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '192 hours'),
  ('fe3b8219-bac3-439a-acb1-bdc198ffa32e', true, 'Luna Pixelheart', 22, 'Woman', 'Man', 'Seattle, WA', 'Anime Scholar', 'Studio Ghibli is a personality.', 'Illustrator who cries at every Miyazaki movie. Looking for someone to argue about sub vs dub (sub, obviously).', array['Anime', 'Watercolor', 'Boba'], '{"hair":"#e8e1d9","skin":"#e7a978","bg":["#1e1b4b","#7c3aed"],"glasses":"square","frame":"#1e3a8a","hairStyle":"swoop","teeth":"buck","freckles":false,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '240 hours'),
  ('61b79ea3-9831-4a2f-a70a-ef1f1983cf55', true, 'Rex Dungeonson', 29, 'Man', 'Woman', 'Denver, CO', 'Lore Keeper', 'Your DM. Roll for initiative.', 'Running a 4-year homebrew campaign. I own 312 dice and I know each one by name. Chaotic good, lawful snacks.', array['D&D', 'Tolkien', 'Hiking'], '{"hair":"#d9480f","skin":"#f6c79d","bg":["#1e1b4b","#7c3aed"],"glasses":"thick","frame":"#9d174d","hairStyle":"bowl","teeth":"one","freckles":true,"mood":"smug"}'::jsonb, false, 0, 0, 0, now() - interval '288 hours'),
  ('705c2529-80b2-4b9d-a0f5-0d4d72a6c0ad', true, 'Kiki Nakamura', 25, 'Woman', 'Man', 'San Francisco, CA', 'Speedrunner', 'Any% world record holder (in my heart).', 'I can beat Super Metroid in 47 minutes and still be late to brunch. Frame-perfect texting, sometimes.', array['Speedruns', 'Celeste', 'Ramen'], '{"hair":"#d9480f","skin":"#6e4428","bg":["#1e1b4b","#7c3aed"],"glasses":"thick","frame":"#1e3a8a","hairStyle":"curly","teeth":"one","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '336 hours'),
  ('2350f42e-1554-49a8-aa1b-bf18ba865417', true, 'Theo Primes', 23, 'Man', 'Woman', 'Boston, MA', 'Math Olympian', 'I find you irrational. In a good way.', 'Math tutor. I will absolutely explain why 0.999... equals 1 on the first date. You have been warned.', array['Number theory', 'Chess', 'Jazz'], '{"hair":"#6b3e26","skin":"#9a6440","bg":["#1e1b4b","#7c3aed"],"glasses":"thick","frame":"#9d174d","hairStyle":"bowl","teeth":"buck","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '5 hours'),
  ('496e6cdf-42b3-4d23-ad0a-b5ad30fe048a', true, 'Juniper Vale', 26, 'Non-binary', 'Everyone', 'Portland, OR', 'Lab Rat', 'Mushrooms are the internet of the forest.', 'Mycologist & amateur radio operator. My call sign is cooler than your call sign. Plant parent to 41 succulents.', array['Mycology', 'Vinyl', 'Foraging'], '{"hair":"#ff6a1a","skin":"#f6c79d","bg":["#0ea5e9","#b6f23a"],"glasses":"thick","frame":"#065f46","hairStyle":"curly","teeth":"grin","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '432 hours'),
  ('4d4b8def-f4be-4097-a338-2733bfad06f9', true, 'Gus Kernel', 31, 'Man', 'Woman', 'Chicago, IL', 'Code Wizard', 'I use Arch btw.', 'Kernel hacker. I have strong opinions about tabs vs spaces and even stronger ones about deep dish.', array['Linux', 'Vim', 'Coffee'], '{"hair":"#ff6a1a","skin":"#ffd9b8","bg":["#ff7a1a","#ff4d8d"],"glasses":"round","frame":"#065f46","hairStyle":"curly","teeth":"one","freckles":false,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '480 hours'),
  ('b860c7a1-6dae-4f1d-a294-c9d05aadc0dd', true, 'Priya Nebula', 24, 'Woman', 'Man', 'Houston, TX', 'Lab Rat', 'Rocket scientist. Literally.', 'Propulsion engineer. I have launched 14 rockets in Kerbal and 2 in real life. Looking for my co-pilot.', array['Astronomy', 'KSP', 'Salsa'], '{"hair":"#22d3ee","skin":"#e7a978","bg":["#1e1b4b","#7c3aed"],"glasses":"thick","frame":"#b45309","hairStyle":"curly","teeth":"buck","freckles":false,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '528 hours'),
  ('fddf191b-cc2a-46e1-a4c4-cf5fa0862638', true, 'Otto Checkmate', 28, 'Man', 'Woman', 'Minneapolis, MN', 'Chess Goblin', '1800 Elo, 0 rizz. Fixable?', 'I play the Bongcloud unironically. My love language is sending you a mate-in-three at 2am.', array['Chess', 'Puzzles', 'Board games'], '{"hair":"#f2c14e","skin":"#f6c79d","bg":["#14532d","#b6f23a"],"glasses":"thick","frame":"#7f1d1d","hairStyle":"spiky","teeth":"buck","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '576 hours'),
  ('8a6d514b-90ba-4051-a18d-07a122fd3453', true, 'Zara Circuit', 23, 'Woman', 'Man', 'Los Angeles, CA', 'Code Wizard', 'Hardware hacker with a soldering iron heart.', 'I built LED wings for my cosplay that sync to music. Currently building a robot that makes perfect pancakes.', array['Arduino', 'Cosplay', 'EDM'], '{"hair":"#8b5cf6","skin":"#c68657","bg":["#1e1b4b","#7c3aed"],"glasses":"thick","frame":"#9d174d","hairStyle":"long","teeth":"one","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '10 hours'),
  ('a5a098da-044b-4f16-af53-ab798d7595b7', true, 'Felix Hexa', 26, 'Man', 'Woman', 'Miami, FL', 'Crypto Degen', 'Down bad but diamond-handed.', 'Bought the top, held the bottom, still smiling. I read whitepapers for fun and charts for emotional damage.', array['Solana', 'Memes', 'Surfing'], '{"hair":"#6b3e26","skin":"#9a6440","bg":["#1e1b4b","#7c3aed"],"glasses":"square","frame":"#1e3a8a","hairStyle":"long","teeth":"one","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '672 hours'),
  ('21ecf9aa-8bcc-405f-aec2-25970c03f6ee', true, 'Mei Lin Opcode', 27, 'Woman', 'Everyone', 'New York, NY', 'Math Olympian', 'Statistically, you should message me.', 'Data scientist. I ran a regression on my dating life. Results were not significant. Help me change that.', array['Statistics', 'Sudoku', 'Dumplings'], '{"hair":"#e8e1d9","skin":"#ffd9b8","bg":["#8b5cf6","#22d3ee"],"glasses":"round","frame":"#111827","hairStyle":"long","teeth":"one","freckles":true,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '720 hours'),
  ('09f463e3-e027-41be-a6b8-be495ea5520e', true, 'Bram Scroll', 30, 'Man', 'Woman', 'Philadelphia, PA', 'Lore Keeper', 'Fantasy novel hoarder. 900+ books.', 'Librarian (the cool kind). I can recite the full line of succession for three fictional kingdoms.', array['Fantasy', 'Calligraphy', 'History'], '{"hair":"#f2c14e","skin":"#ffd9b8","bg":["#312e81","#ff7a1a"],"glasses":"round","frame":"#7f1d1d","hairStyle":"bowl","teeth":"one","freckles":true,"mood":"smug"}'::jsonb, false, 0, 0, 0, now() - interval '768 hours'),
  ('8537e46e-9559-4c00-a24b-1858f08fe12c', true, 'Nova Ramirez', 22, 'Woman', 'Man', 'Phoenix, AZ', 'Speedrunner', 'Glitch hunter. Wall-clipper. Menace.', 'I find glitches in games and in people. Mostly harmless. Owns every Nintendo console ever made.', array['Retro games', 'Skateboarding', 'Tacos'], '{"hair":"#6b3e26","skin":"#f6c79d","bg":["#ff4d8d","#8b5cf6"],"glasses":"square","frame":"#1e3a8a","hairStyle":"bowl","teeth":"one","freckles":true,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '816 hours'),
  ('8103b686-4c47-44bb-a367-1dbef184eed2', true, 'Idris Vector', 25, 'Man', 'Woman', 'Atlanta, GA', 'Anime Scholar', 'One Piece is real.', 'Making lo-fi beats and reading manga until 4am. Will fight for Zoro. Looking for my nakama.', array['Manga', 'Basketball', 'Beats'], '{"hair":"#ff6a1a","skin":"#f6c79d","bg":["#f59e0b","#ef4444"],"glasses":"thick","frame":"#111827","hairStyle":"swoop","teeth":"grin","freckles":true,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '15 hours'),
  ('dd449694-ac2c-4366-a657-8dfc38253fda', true, 'Sol Achebe', 28, 'Non-binary', 'Everyone', 'Oakland, CA', 'Crypto Degen', 'On-chain and off the charts.', 'Smart contract auditor who writes haiku about reentrancy bugs. Gas fees are my love language.', array['DeFi', 'Poetry', 'Jazz'], '{"hair":"#111","skin":"#e7a978","bg":["#ff7a1a","#ff4d8d"],"glasses":"square","frame":"#1f2937","hairStyle":"long","teeth":"grin","freckles":true,"mood":"smug"}'::jsonb, false, 0, 0, 0, now() - interval '912 hours'),
  ('c475aa5d-1e2b-4795-a465-8e06c67dcdc1', true, 'Hazel Tensor', 26, 'Woman', 'Man', 'Pittsburgh, PA', 'Code Wizard', 'Training models, not relationships (yet).', 'AI researcher who knits sweaters for her cats. Both are overfitting. Tell me your favorite loss function.', array['ML', 'Knitting', 'Cats'], '{"hair":"#e8e1d9","skin":"#e7a978","bg":["#14532d","#b6f23a"],"glasses":"thick","frame":"#7f1d1d","hairStyle":"curly","teeth":"buck","freckles":false,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '960 hours'),
  ('de04a264-76c7-484c-a1e1-392d5b8da1b2', true, 'Wes Polygon', 24, 'Man', 'Woman', 'Salt Lake City, UT', 'Speedrunner', 'Low-poly artist, high-effort friend.', 'Making an indie game about a frog who wants to be an astronaut. Wishlist it. Or me. Either works.', array['Blender', 'Indie games', 'Climbing'], '{"hair":"#8b5cf6","skin":"#ffd9b8","bg":["#ff7a1a","#ff4d8d"],"glasses":"thick","frame":"#9d174d","hairStyle":"spiky","teeth":"buck","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '1008 hours'),
  ('1222bd53-094a-4b7a-a480-3ec3fff18e92', true, 'Ivy Sigma', 23, 'Woman', 'Man', 'Nashville, TN', 'Chess Goblin', 'I will checkmate you and then buy you coffee.', 'Chess streamer (47 followers, all legends). Bakes a mean sourdough. Plays the Sicilian, emotionally too.', array['Chess', 'Country music', 'Baking'], '{"hair":"#ff4d8d","skin":"#9a6440","bg":["#312e81","#ff7a1a"],"glasses":"square","frame":"#9d174d","hairStyle":"spiky","teeth":"grin","freckles":false,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '1056 hours'),
  ('c215dc5c-f5de-47c3-a631-38eb403f1d68', true, 'Arjun Delta', 29, 'Man', 'Woman', 'San Diego, CA', 'Math Olympian', 'Calculus got me through heartbreak.', 'Physics teacher. My students call me Mr. Derivative. My mom calls me single. Help me prove her wrong.', array['Calculus', 'Cricket', 'Chai'], '{"hair":"#2b1d14","skin":"#ffd9b8","bg":["#ff4d8d","#8b5cf6"],"glasses":"thick","frame":"#1f2937","hairStyle":"spiky","teeth":"one","freckles":true,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '20 hours'),
  ('4cc286de-f1f3-4d23-a3d7-21b0b950d20e', true, 'Robin Glitch', 27, 'Non-binary', 'Everyone', 'Detroit, MI', 'Code Wizard', 'Pixel art & punk rock.', 'Makes pixel art zines and 8-bit covers of punk songs. Very loud, very soft. Pet: one extremely judgmental ferret.', array['Pixel art', 'Punk', 'Zines'], '{"hair":"#111","skin":"#f6c79d","bg":["#ff7a1a","#ff4d8d"],"glasses":"round","frame":"#065f46","hairStyle":"long","teeth":"one","freckles":false,"mood":"shock"}'::jsonb, false, 0, 0, 0, now() - interval '1152 hours'),
  ('a4a17d13-442c-4773-a96b-dacb95d8dbfa', true, 'Clara Orbit', 25, 'Woman', 'Man', 'Orlando, FL', 'Lab Rat', 'Marine biologist. Octopus defender.', 'I study cephalopods. Octopuses have 9 brains and still can’t figure out dating either. We are the same.', array['Oceans', 'Diving', 'Sci-fi'], '{"hair":"#8b5cf6","skin":"#9a6440","bg":["#1e1b4b","#7c3aed"],"glasses":"square","frame":"#111827","hairStyle":"curly","teeth":"grin","freckles":true,"mood":"smug"}'::jsonb, false, 0, 0, 0, now() - interval '1200 hours'),
  ('30b23920-6c61-4a31-a0e2-a6489712e454', true, 'Dex Mainframe', 32, 'Man', 'Woman', 'Seattle, WA', 'Lore Keeper', 'Star Trek > Star Wars. Fight me (gently).', 'Collects vintage computers. My Commodore 64 still boots. So does my heart, eventually. Makes a mean lasagna.', array['Star Trek', 'Retro PCs', 'Cooking'], '{"hair":"#6b3e26","skin":"#9a6440","bg":["#ff7a1a","#ff4d8d"],"glasses":"thick","frame":"#7f1d1d","hairStyle":"curly","teeth":"grin","freckles":false,"mood":"happy"}'::jsonb, false, 0, 0, 0, now() - interval '1248 hours')
on conflict (id) do nothing;
